### ISSUE TITLE
filename character length limitation bug

### ISSUE THREAD

**Issue by yucelkilic** [tubitaktug/tuglib#1]
https://github.com/tubitaktug/tuglib/blob/5dc8f628a7e7257fb9de24bdbc1b3c37f8018002/tuglib/reduction/helper.py#L188

This value should be greater than 64 characters.

**Comment by ookuyan** [comment]
Line => 188: This length (U64) value is for "fits" header keyword. 64 characters are often sufficient.

To change the length of the file name in the table, I changed the following line to an appropriate value.

Line => 466: "dtypes = ['U64'] + dtypes" to "dtypes = ['U256'] + dtypes"
